import ReactPDF, {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from '@react-pdf/renderer';
import { InterviewBrief } from '@/types/prepare';

// Define styles for the PDF
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    fontSize: 10,
    lineHeight: 1.4,
    color: '#000000',
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: '#1B4332',
    paddingBottom: 10,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 4,
    color: '#1B4332',
  },
  subtitle: {
    fontSize: 11,
    color: '#333333',
    marginBottom: 2,
  },
  formatBadge: {
    fontSize: 9,
    color: '#666666',
    marginTop: 4,
  },
  section: {
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 6,
    color: '#1B4332',
    textTransform: 'uppercase',
  },
  sectionContent: {
    fontSize: 10,
    lineHeight: 1.5,
    color: '#000000',
    marginBottom: 6,
  },
  tipsContainer: {
    marginTop: 6,
    paddingLeft: 10,
    borderLeftWidth: 2,
    borderLeftColor: '#1B4332',
  },
  tipsHeader: {
    fontSize: 9,
    fontWeight: 'bold',
    color: '#1B4332',
    marginBottom: 3,
  },
  tip: {
    fontSize: 9,
    color: '#333333',
    marginBottom: 2,
    marginLeft: 5,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: '#666666',
    textAlign: 'center',
    borderTopWidth: 1,
    borderTopColor: '#CCCCCC',
    paddingTop: 10,
  },
});

interface BriefDocumentProps {
  brief: InterviewBrief;
  companyName: string;
  jobTitle: string;
}

// Create the PDF document component
const BriefDocument = ({ brief, companyName, jobTitle }: BriefDocumentProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.title}>Interview Preparation Brief</Text>
        <Text style={styles.subtitle}>{companyName} - {jobTitle}</Text>
        <Text style={styles.formatBadge}>
          {brief.format === '30min' ? '30-Minute Interview' : '60-Minute Interview'}
        </Text>
      </View>

      {/* Sections */}
      {brief.sections.map((section, index) => (
        <View key={index} style={styles.section}>
          <Text style={styles.sectionTitle}>{section.title}</Text>

          {/* Section Content */}
          <View style={styles.sectionContent}>
            {section.content.split('\n').map((line, lineIndex) => {
              const trimmedLine = line.trim();
              if (!trimmedLine) return null;
              return <Text key={lineIndex}>{trimmedLine}</Text>;
            })}
          </View>

          {/* Tips */}
          {section.tips && section.tips.length > 0 && (
            <View style={styles.tipsContainer}>
              <Text style={styles.tipsHeader}>Tips:</Text>
              {section.tips.map((tip, tipIndex) => (
                <Text key={tipIndex} style={styles.tip}>• {tip}</Text>
              ))}
            </View>
          )}
        </View>
      ))}

      {/* Footer */}
      <View style={styles.footer}>
        <Text>Generated by Resolut • {new Date(brief.generatedAt).toLocaleDateString()}</Text>
      </View>
    </Page>
  </Document>
);

export async function generateBriefPDF(
  brief: InterviewBrief,
  companyName: string,
  jobTitle: string
): Promise<Buffer> {
  try {
    const pdfStream = await ReactPDF.renderToStream(
      <BriefDocument brief={brief} companyName={companyName} jobTitle={jobTitle} />
    );

    // Convert stream to buffer
    const chunks: Uint8Array[] = [];

    return new Promise((resolve, reject) => {
      pdfStream.on('data', (chunk: Uint8Array) => chunks.push(chunk));
      pdfStream.on('end', () => resolve(Buffer.concat(chunks)));
      pdfStream.on('error', reject);
    });
  } catch (error) {
    throw new Error(
      `Failed to generate PDF: ${error instanceof Error ? error.message : 'Unknown error'}`
    );
  }
}
